第９講課題提出
kazuoikeda1411/lecture09 pull request #2
Opened 2022-12-14 13:21 UTC by kazuoikeda1411

# 概要
第９講課題提出を提出いたします。
データベースの詳細、実装内容、実装結果は以下に記載致しました。
ご確認お願いいたします🙇

# データベースの詳細
![image](https://user-images.githubusercontent.com/118358124/207526984-79c468cb-1bf7-4789-b25f-ce01b9aaddb6.png)

# MyBatisによるREADの実装（serviceクラスの追加）
以下を実装しました。
1.nameの全件検索を実装しJSON形式(id,name,disease)で返す
2.クエリでdiseaseを入力しアクセスするとDBからdiseaseを条件検索し、対象のnameを返す

# READ実装結果
1.nameの全件検索を実装しJSON形式(id,name,disease)で返す
![image](https://user-images.githubusercontent.com/118358124/207536665-52d786f6-7810-4baa-8f20-49e55f67b8a9.png)

2.クエリでdiseaseを入力しアクセスするとDBからdiseaseを条件検索し、対象のnameを返す
![image](https://user-images.githubusercontent.com/118358124/207536819-7ac4010e-2090-459d-9580-c860185a5099.png)

2022-12-15 13:56 UTC, YudaiNoda3576 reviewed
コメントしています！

2022-12-15 13:56 UTC, YudaiNoda3576 commented on src/main/java/com/raisetech/lecture09/Disease.java
> +public record Disease(String name, String disease) {
Recordを使用されてるのナイスですね:+1:

2022-12-15 13:56 UTC, YudaiNoda3576 commented on src/main/java/com/raisetech/lecture09/service/MedicalRecordImpl.java
> +public class MedicalRecordImpl implements MedicalRecordService {
ここのクラス名は`MedicalRecordServiceImpl`が妥当かと思います!

2022-12-15 13:56 UTC, YudaiNoda3576 commented on src/main/java/com/raisetech/lecture09/service/MedicalRecordImpl.java
> +	public List<DiseaseResponse> byDisease() {
他のメソッドには`find`がプレフィックスとしてついているので`findByDesease`が妥当かなと思うのですがいかがでしょうか？

2022-12-15 13:56 UTC, YudaiNoda3576 commented on src/main/java/com/raisetech/lecture09/service/MedicalRecordImpl.java
> +		return null;
`null` を返しているのはどのような理由がありますか？？

2022-12-15 13:56 UTC, YudaiNoda3576 commented on src/main/resources/application.properties
> +spring.datasource.username=user
認証情報に関しては環境変数を使用するなどして隠蔽するようにしましょう！

FYI
https://www.notion.so/DB-0d1a9cd93e084c47a767b8fe16b729bb

2022-12-15 13:56 UTC, YudaiNoda3576 commented on src/main/java/com/raisetech/lecture09/MedicalRecordController.java
> +public class MedicalRecordController {
MediaclaRecordControllerが２つあると思うのですが、controllerディレクトリ配下のファイルは不要ではないでしょうか？？

2022-12-15 13:56 UTC, YudaiNoda3576 commented on src/main/java/com/raisetech/lecture09/controller/MedicalRecordController.java
> +	public List<String> getPatients(@RequestParam(value="disease") String disease) {
nullが返ってくることがあると思うのですが、その処理は追加しなくても大丈夫そうですか？？

2022-12-17 09:06 UTC, kazuoikeda1411 commented on src/main/java/com/raisetech/lecture09/service/MedicalRecordImpl.java
> +public class MedicalRecordImpl implements MedicalRecordService {
`MedicalRecordServiceImpl`に修正しました！

2022-12-17 09:09 UTC, kazuoikeda1411 commented on src/main/java/com/raisetech/lecture09/service/MedicalRecordImpl.java
> +	public List<DiseaseResponse> byDisease() {
`findByDesease `へ修正しました！

2022-12-17 09:11 UTC, kazuoikeda1411 commented on src/main/java/com/raisetech/lecture09/service/MedicalRecordImpl.java
> +		return null;
`return null`はIDEに従って記載しておりました。
実装で欲しい結果が出てきていたのでで、修正せずそのままにしてしましました。
`findByDisease()`を返すようコードを修正しました。

2022-12-17 09:13 UTC, kazuoikeda1411 commented on src/main/resources/application.properties
> +spring.datasource.username=user
Java質問相談所にて質問していた通りに対応しました！
`spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}`

また環境変数を設定して、問題なく実装できております🙇

2022-12-17 09:15 UTC, kazuoikeda1411 commented on src/main/java/com/raisetech/lecture09/MedicalRecordController.java
> +public class MedicalRecordController {
feature/readブランチにpushするときに色々やっていた時に残ってしまっていたようです。申し訳ございません。
以下で不要なファイルについては削除しておりますのでご確認いただけますと幸いです。

2022-12-17 09:17 UTC, kazuoikeda1411 commented on src/main/java/com/raisetech/lecture09/controller/MedicalRecordController.java
> +	public List<String> getPatients(@RequestParam(value="disease") String disease) {
nullに関して例外処理を追加実装しました！
実装結果は以下の通りです。
![image](https://user-images.githubusercontent.com/118358124/208234956-319eb160-c466-497a-a051-239f0d6d5b8b.png)

2022-12-17 09:29 UTC, kazuoikeda1411 commented
コメントに対する修正対応を行いました。
ご確認お願いいたします！

修正内容
・クラス等の命名の変更
・Service実装に対する修正
・認証情報の隠蔽
・例外処理の追加
・ディレクトリ内のファイルの整理
・Mapperファイル名の変更

2022-12-18 02:10 UTC, YudaiNoda3576 reviewed
コメントしています〜

2022-12-18 02:10 UTC, YudaiNoda3576 commented on src/main/java/com/raisetech/lecture09/service/MedicalRecordImpl.java
> +		return null;
> return nullはIDEに従って記載

自動補完に従ったということですかね？？

> 実装で欲しい結果が出てきていた

これってなんでその結果が返ってきていたか理由はわかりますか...?

2022-12-18 02:15 UTC, YudaiNoda3576 requested changes
コメントしています〜

2022-12-18 02:15 UTC, YudaiNoda3576 commented on src/main/java/com/raisetech/lecture09/controller/MedicalRecordController.java
> +		if (medicalRecordService.findByDisease(disease).isEmpty()) {
こういったロジックをControllerクラスにはあまり持ち込みたくないですね！
例外処理の部分をServiceImplに移行できないか検討してみてください！

2022-12-18 02:15 UTC, YudaiNoda3576 commented on src/main/java/com/raisetech/lecture09/controller/MedicalRecordResponse.java
> +public class MedicalRecordResponse {
Responseを独自のObjectに格納して返却するいいですね！
ナイストライです！:+1:
参考までにResponseEntityというクラスを使用することでも同じようなことができます:pray:

FYI
https://spring.pleiades.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html

気になるのが,Controllerディレクトリ配下に置かれている点です。
responsesみたいなディレクトリを切って、そこに置くのが良いかと思いますので修正となぜそうするのかという理由をご共有ください！

2022-12-20 04:10 UTC, kazuoikeda1411 commented
コメントに対する修正対応を行いました。
ご確認お願いいたします！

修正内容
・例外処理をServiceクラスに移行
・responceディレクトリ・exeptionディレクトリを作成し、各ファイルを再配置
・コントローラークラスのコンストラクタをMedicalRecordMapper→MedicalRecordServiceに参照を変更した

2022-12-20 04:15 UTC, kazuoikeda1411 commented on src/main/java/com/raisetech/lecture09/service/MedicalRecordImpl.java
> +		return null;
自動保管に従ってしまいました。
コントローラークラスのコンストラクタの定義が間違っていたため、ここでnullを返していても問題なく作動していたのではないかと考えました。
またのfindByDiseaseメソッドで新たに返すリストを作成（上書き？）しているため、serviceクラスのメソッドにnullが返ってきていても、ほしい結果が返ってきたのではないかとも考えました。

理由として間違いがありましたらご指摘いただけますと幸いです。

2022-12-20 04:18 UTC, kazuoikeda1411 commented on src/main/java/com/raisetech/lecture09/controller/MedicalRecordController.java
> +		if (medicalRecordService.findByDisease(disease).isEmpty()) {
例外処理の部分をServiceImplに移行しました。ま例外処理に関するクラス（ExceptionHandler等）をexeptionディレクトリにまとめました。

2022-12-20 04:18 UTC, kazuoikeda1411 commented on src/main/java/com/raisetech/lecture09/controller/MedicalRecordResponse.java
> +public class MedicalRecordResponse {
responsesディレクトリにレスポンスをまとめて配置しました！

2022-12-20 06:14 UTC, YudaiNoda3576 commented
![LGTM](https://image.lgtmoon.dev/191680)

2022-12-20 23:45 UTC, merged